language:
  python

python:
  - 3.4

install:
  - pip install --upgrade -r requirements.dev.txt

script:
  - pylama authz
  - nosetests tests -sv --with-coverage --cover-package authz

after_success:
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: eRuM1eRI/ZcLUQpdGzP4190QLc3/g7WRG0X0ujdLy5OhGhVCB6cq7OGgF4dhzn0A4dBrkkW86u9VmBkgncGeRVTP7Q9jBC8YeizTJwJIP7a/2LErK1Z8PGeiICHk/slVvYME2gWyNtd+dnw7lChOWphIvcKE7pY32JFyG8zhsJkLX8PtMG0AfDyjNAL/Dgo8B6wQ/N/+UBopyG18u+hUhh5VRzBkHz7uqqQGTq2TkDp/UUwI7xiEnupK65kGK/mnBfLU3KyzGYd7uyPCuFyV0nHwJL30oSb9n7O/WzUYaHi6pfVWgaG3FKKwSdu80YFo8DgQE5yLTUmz6lZ9GXsl03FeyMy0RZmhXpcOZsv/H5UTowmGIUwNyF00A77gnEa51DxozcrpH7Aa8SwZ97Uq3qzlG7JSFQWFb5VXlv6/XbOGuxMpXHRt8A+efjHo6ppwtrYs2GWwuISFdYg9bB1L7kXF9LnVCNl9ycjgKe49LraeLhTefiyfgBfXKKfQPFYFvLk+UU93f94PmSWR2GwNyq+F0kE71X6RodYU+dgBCglPNpqZ1jMIWlS6UR/PlwMNbENxYoMjqj1DyxWQKOHU63q+aTwdhaBx6AY/9IftyVJq9gn7z2SpQzyBnYdw92TrG52uFfNnt0eXpPGuj0CQC/RLlYUNCq/aFCGoVlJEFh4=
  app: test-openspending
