# General
port: 5000
debug: true
api_key_whitelist: ''
openspending_access_key_id: ''
openspending_secret_access_key: ''
openspending_storage_bucket_name: ''
openspending_s3_hostname: 's3.amazonaws.com'
aws_s3_custom_domain: 'https://storage.openspending.org'
aws_s3_secure_urls: true
aws_querysting_auth: false
access_key_expires_in: 259200 # 3 days

# Browsersync
browsersync:
  port: 4200
  ui:
    port: 4201
